#!/bin/sh

ngx_addon_name=ngx_conf_script

ngx_module_name=ngx_conf_script_module
ngx_module_type=CORE
ngx_module_srcs="$ngx_addon_dir/ngx_conf_def.c $ngx_addon_dir/ngx_conf_script_module.c $ngx_addon_dir/ngx_conf_script_functions.c"
ngx_module_incs="$ngx_addon_dir"
ngx_module_deps="$ngx_addon_dir/ngx_conf_def.h"
. auto/module

patchcore()
{
	local patches= p
	
	p="complex_value_in_include"
	patches="$patches $p"
	
	p="complex_value_in_http_complex_value"
	patches="$patches $p"
	
	p="complex_value_in_set_str_slot"
	patches="$patches $p"
	
	p="complex_value_in_set_str_array_slot"
	patches="$patches $p"
	
	p="complex_value_in_root"
	patches="$patches $p"
	
	p="complex_value_in_server_name"
	patches="$patches $p"
	
	p="delim_init"
	patches="$patches $p"
	
	p="block_level"
	patches="$patches $p"
	
	p="ngx_conf_script_block_start_and_done"
	patches="$patches $p"
	
	for p in $patches
	do
		patch -p1 < "$ngx_addon_dir/patches/$p.patch" || exit 1
	done
}

patchcore
