#!/bin/sh

ngx_addon_name=ngx_conf_script

ngx_module_name=ngx_conf_script_module
ngx_module_type=CORE
ngx_module_srcs="$ngx_addon_dir/ngx_conf_def.c $ngx_addon_dir/ngx_conf_script_module.c"
ngx_module_incs="$ngx_addon_dir"
ngx_module_deps="$ngx_addon_dir/ngx_conf_def.h"
. auto/module

patchcore()
{
	local p="nginx.defs.patch"
	patch -p1 < "$ngx_addon_dir/$p" || exit 1
}

patchcore
